export const componentsName = {
  app: "app",
  screen: "screen",
  box: "box",
  text: "text",
  // button: "button",
  // input: "input",
  // label: "label",
  // toggle: "toggle",
  // navBar: "navBar",
  // title: "title",
  // dropdown: "dropdown",
  // table: "table",
  // message: "message",
  // dialog: "dialog",
  // card: "card",
  // textDelete: "textDelete",
  // link: "link",
  // errorBoundaryUI: "errorBoundaryUI",
  // fontCard: "fontCard",
  // toast: "toast",
};
